// Generated by gencpp from file robotics_project/MoveHeadRequest.msg
// DO NOT EDIT!


#ifndef ROBOTICS_PROJECT_MESSAGE_MOVEHEADREQUEST_H
#define ROBOTICS_PROJECT_MESSAGE_MOVEHEADREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotics_project
{
template <class ContainerAllocator>
struct MoveHeadRequest_
{
  typedef MoveHeadRequest_<ContainerAllocator> Type;

  MoveHeadRequest_()
    : motion()  {
    }
  MoveHeadRequest_(const ContainerAllocator& _alloc)
    : motion(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _motion_type;
  _motion_type motion;





  typedef boost::shared_ptr< ::robotics_project::MoveHeadRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotics_project::MoveHeadRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveHeadRequest_

typedef ::robotics_project::MoveHeadRequest_<std::allocator<void> > MoveHeadRequest;

typedef boost::shared_ptr< ::robotics_project::MoveHeadRequest > MoveHeadRequestPtr;
typedef boost::shared_ptr< ::robotics_project::MoveHeadRequest const> MoveHeadRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotics_project::MoveHeadRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotics_project::MoveHeadRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotics_project::MoveHeadRequest_<ContainerAllocator1> & lhs, const ::robotics_project::MoveHeadRequest_<ContainerAllocator2> & rhs)
{
  return lhs.motion == rhs.motion;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotics_project::MoveHeadRequest_<ContainerAllocator1> & lhs, const ::robotics_project::MoveHeadRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotics_project

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robotics_project::MoveHeadRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotics_project::MoveHeadRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotics_project::MoveHeadRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotics_project::MoveHeadRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotics_project::MoveHeadRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotics_project::MoveHeadRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotics_project::MoveHeadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "56c5b2babfc4b27e5a596091bb964bc2";
  }

  static const char* value(const ::robotics_project::MoveHeadRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x56c5b2babfc4b27eULL;
  static const uint64_t static_value2 = 0x5a596091bb964bc2ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotics_project::MoveHeadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotics_project/MoveHeadRequest";
  }

  static const char* value(const ::robotics_project::MoveHeadRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotics_project::MoveHeadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string motion\n"
;
  }

  static const char* value(const ::robotics_project::MoveHeadRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotics_project::MoveHeadRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motion);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveHeadRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotics_project::MoveHeadRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotics_project::MoveHeadRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "motion: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.motion);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTICS_PROJECT_MESSAGE_MOVEHEADREQUEST_H
