// Generated by gencpp from file robotics_project/PickUpPoseResult.msg
// DO NOT EDIT!


#ifndef ROBOTICS_PROJECT_MESSAGE_PICKUPPOSERESULT_H
#define ROBOTICS_PROJECT_MESSAGE_PICKUPPOSERESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotics_project
{
template <class ContainerAllocator>
struct PickUpPoseResult_
{
  typedef PickUpPoseResult_<ContainerAllocator> Type;

  PickUpPoseResult_()
    : error_code(0)  {
    }
  PickUpPoseResult_(const ContainerAllocator& _alloc)
    : error_code(0)  {
  (void)_alloc;
    }



   typedef int32_t _error_code_type;
  _error_code_type error_code;





  typedef boost::shared_ptr< ::robotics_project::PickUpPoseResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotics_project::PickUpPoseResult_<ContainerAllocator> const> ConstPtr;

}; // struct PickUpPoseResult_

typedef ::robotics_project::PickUpPoseResult_<std::allocator<void> > PickUpPoseResult;

typedef boost::shared_ptr< ::robotics_project::PickUpPoseResult > PickUpPoseResultPtr;
typedef boost::shared_ptr< ::robotics_project::PickUpPoseResult const> PickUpPoseResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotics_project::PickUpPoseResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotics_project::PickUpPoseResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotics_project::PickUpPoseResult_<ContainerAllocator1> & lhs, const ::robotics_project::PickUpPoseResult_<ContainerAllocator2> & rhs)
{
  return lhs.error_code == rhs.error_code;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotics_project::PickUpPoseResult_<ContainerAllocator1> & lhs, const ::robotics_project::PickUpPoseResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotics_project

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robotics_project::PickUpPoseResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotics_project::PickUpPoseResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotics_project::PickUpPoseResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotics_project::PickUpPoseResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotics_project::PickUpPoseResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotics_project::PickUpPoseResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotics_project::PickUpPoseResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea324a22c787839f822b9a025bc2c6fe";
  }

  static const char* value(const ::robotics_project::PickUpPoseResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea324a22c787839fULL;
  static const uint64_t static_value2 = 0x822b9a025bc2c6feULL;
};

template<class ContainerAllocator>
struct DataType< ::robotics_project::PickUpPoseResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotics_project/PickUpPoseResult";
  }

  static const char* value(const ::robotics_project::PickUpPoseResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotics_project::PickUpPoseResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"# Comes from moveit_msgs/MoveItErrorCodes\n"
"int32 error_code\n"
;
  }

  static const char* value(const ::robotics_project::PickUpPoseResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotics_project::PickUpPoseResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.error_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PickUpPoseResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotics_project::PickUpPoseResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotics_project::PickUpPoseResult_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "error_code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.error_code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTICS_PROJECT_MESSAGE_PICKUPPOSERESULT_H
