// Generated by gencpp from file irob_assignment_1/GetNextGoalFeedback.msg
// DO NOT EDIT!


#ifndef IROB_ASSIGNMENT_1_MESSAGE_GETNEXTGOALFEEDBACK_H
#define IROB_ASSIGNMENT_1_MESSAGE_GETNEXTGOALFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_msgs/Path.h>

namespace irob_assignment_1
{
template <class ContainerAllocator>
struct GetNextGoalFeedback_
{
  typedef GetNextGoalFeedback_<ContainerAllocator> Type;

  GetNextGoalFeedback_()
    : gain(0.0)
    , path()  {
    }
  GetNextGoalFeedback_(const ContainerAllocator& _alloc)
    : gain(0.0)
    , path(_alloc)  {
  (void)_alloc;
    }



   typedef double _gain_type;
  _gain_type gain;

   typedef  ::nav_msgs::Path_<ContainerAllocator>  _path_type;
  _path_type path;





  typedef boost::shared_ptr< ::irob_assignment_1::GetNextGoalFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::irob_assignment_1::GetNextGoalFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct GetNextGoalFeedback_

typedef ::irob_assignment_1::GetNextGoalFeedback_<std::allocator<void> > GetNextGoalFeedback;

typedef boost::shared_ptr< ::irob_assignment_1::GetNextGoalFeedback > GetNextGoalFeedbackPtr;
typedef boost::shared_ptr< ::irob_assignment_1::GetNextGoalFeedback const> GetNextGoalFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::irob_assignment_1::GetNextGoalFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::irob_assignment_1::GetNextGoalFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::irob_assignment_1::GetNextGoalFeedback_<ContainerAllocator1> & lhs, const ::irob_assignment_1::GetNextGoalFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.gain == rhs.gain &&
    lhs.path == rhs.path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::irob_assignment_1::GetNextGoalFeedback_<ContainerAllocator1> & lhs, const ::irob_assignment_1::GetNextGoalFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace irob_assignment_1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::irob_assignment_1::GetNextGoalFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::irob_assignment_1::GetNextGoalFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::irob_assignment_1::GetNextGoalFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::irob_assignment_1::GetNextGoalFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irob_assignment_1::GetNextGoalFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irob_assignment_1::GetNextGoalFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::irob_assignment_1::GetNextGoalFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3fd937c20feb920775439a64b763c7e5";
  }

  static const char* value(const ::irob_assignment_1::GetNextGoalFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3fd937c20feb9207ULL;
  static const uint64_t static_value2 = 0x75439a64b763c7e5ULL;
};

template<class ContainerAllocator>
struct DataType< ::irob_assignment_1::GetNextGoalFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "irob_assignment_1/GetNextGoalFeedback";
  }

  static const char* value(const ::irob_assignment_1::GetNextGoalFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::irob_assignment_1::GetNextGoalFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback definition\n"
"float64 gain\n"
"nav_msgs/Path path\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/Path\n"
"#An array of poses that represents a Path for a robot to follow\n"
"Header header\n"
"geometry_msgs/PoseStamped[] poses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::irob_assignment_1::GetNextGoalFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::irob_assignment_1::GetNextGoalFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gain);
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetNextGoalFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::irob_assignment_1::GetNextGoalFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::irob_assignment_1::GetNextGoalFeedback_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "gain: ";
    Printer<double>::stream(s, indent + "  ", v.gain);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "path: ";
    Printer< ::nav_msgs::Path_<ContainerAllocator> >::stream(s, indent + "  ", v.path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IROB_ASSIGNMENT_1_MESSAGE_GETNEXTGOALFEEDBACK_H
