// Generated by gencpp from file irob_assignment_1/GetSetpoint.msg
// DO NOT EDIT!


#ifndef IROB_ASSIGNMENT_1_MESSAGE_GETSETPOINT_H
#define IROB_ASSIGNMENT_1_MESSAGE_GETSETPOINT_H

#include <ros/service_traits.h>


#include <irob_assignment_1/GetSetpointRequest.h>
#include <irob_assignment_1/GetSetpointResponse.h>


namespace irob_assignment_1
{

struct GetSetpoint
{

typedef GetSetpointRequest Request;
typedef GetSetpointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSetpoint
} // namespace irob_assignment_1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::irob_assignment_1::GetSetpoint > {
  static const char* value()
  {
    return "3629cc8e587b54ab374dc14c83d7aa3e";
  }

  static const char* value(const ::irob_assignment_1::GetSetpoint&) { return value(); }
};

template<>
struct DataType< ::irob_assignment_1::GetSetpoint > {
  static const char* value()
  {
    return "irob_assignment_1/GetSetpoint";
  }

  static const char* value(const ::irob_assignment_1::GetSetpoint&) { return value(); }
};


// service_traits::MD5Sum< ::irob_assignment_1::GetSetpointRequest> should match
// service_traits::MD5Sum< ::irob_assignment_1::GetSetpoint >
template<>
struct MD5Sum< ::irob_assignment_1::GetSetpointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::irob_assignment_1::GetSetpoint >::value();
  }
  static const char* value(const ::irob_assignment_1::GetSetpointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::irob_assignment_1::GetSetpointRequest> should match
// service_traits::DataType< ::irob_assignment_1::GetSetpoint >
template<>
struct DataType< ::irob_assignment_1::GetSetpointRequest>
{
  static const char* value()
  {
    return DataType< ::irob_assignment_1::GetSetpoint >::value();
  }
  static const char* value(const ::irob_assignment_1::GetSetpointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::irob_assignment_1::GetSetpointResponse> should match
// service_traits::MD5Sum< ::irob_assignment_1::GetSetpoint >
template<>
struct MD5Sum< ::irob_assignment_1::GetSetpointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::irob_assignment_1::GetSetpoint >::value();
  }
  static const char* value(const ::irob_assignment_1::GetSetpointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::irob_assignment_1::GetSetpointResponse> should match
// service_traits::DataType< ::irob_assignment_1::GetSetpoint >
template<>
struct DataType< ::irob_assignment_1::GetSetpointResponse>
{
  static const char* value()
  {
    return DataType< ::irob_assignment_1::GetSetpoint >::value();
  }
  static const char* value(const ::irob_assignment_1::GetSetpointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IROB_ASSIGNMENT_1_MESSAGE_GETSETPOINT_H
