(cl:defpackage irob_assignment_1-msg
  (:use )
  (:export
   "<GETNEXTGOALACTION>"
   "GETNEXTGOALACTION"
   "<GETNEXTGOALACTIONFEEDBACK>"
   "GETNEXTGOALACTIONFEEDBACK"
   "<GETNEXTGOALACTIONGOAL>"
   "GETNEXTGOALACTIONGOAL"
   "<GETNEXTGOALACTIONRESULT>"
   "GETNEXTGOALACTIONRESULT"
   "<GETNEXTGOALFEEDBACK>"
   "GETNEXTGOALFEEDBACK"
   "<GETNEXTGOALGOAL>"
   "GETNEXTGOALGOAL"
   "<GETNEXTGOALRESULT>"
   "GETNEXTGOALRESULT"
  ))

