; Auto-generated. Do not edit!


(cl:in-package irob_assignment_1-msg)


;//! \htmlinclude GetNextGoalGoal.msg.html

(cl:defclass <GetNextGoalGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass GetNextGoalGoal (<GetNextGoalGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GetNextGoalGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GetNextGoalGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name irob_assignment_1-msg:<GetNextGoalGoal> is deprecated: use irob_assignment_1-msg:GetNextGoalGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GetNextGoalGoal>) ostream)
  "Serializes a message object of type '<GetNextGoalGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GetNextGoalGoal>) istream)
  "Deserializes a message object of type '<GetNextGoalGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GetNextGoalGoal>)))
  "Returns string type for a message object of type '<GetNextGoalGoal>"
  "irob_assignment_1/GetNextGoalGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GetNextGoalGoal)))
  "Returns string type for a message object of type 'GetNextGoalGoal"
  "irob_assignment_1/GetNextGoalGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GetNextGoalGoal>)))
  "Returns md5sum for a message object of type '<GetNextGoalGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GetNextGoalGoal)))
  "Returns md5sum for a message object of type 'GetNextGoalGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GetNextGoalGoal>)))
  "Returns full string definition for message of type '<GetNextGoalGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal definition~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GetNextGoalGoal)))
  "Returns full string definition for message of type 'GetNextGoalGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal definition~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GetNextGoalGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GetNextGoalGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'GetNextGoalGoal
))
